# Generated by Django 4.2.1 on 2023-07-07 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_views', '0002_alter_commentbaseclass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbaseclass',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
