# Generated by Django 4.2.1 on 2023-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teachrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
