# Generated by Django 4.2 on 2023-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='آدرس ایمیل')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('image', models.ImageField(upload_to='profiles')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن')),
                ('sex', models.CharField(choices=[('man', 'مرد'), ('woman', 'زن'), ('other', 'دیگر')], max_length=5, verbose_name='جنسیت')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
