# Generated by Django 4.2 on 2023-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name='نام کاربری'),
        ),
    ]
