# Generated by Django 4.2.1 on 2023-06-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='آدرس ایمیل'),
        ),
    ]
