# Generated by Django 4.2.1 on 2023-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='نام کاربری'),
        ),
    ]
