# Generated by Django 4.2.1 on 2023-08-16 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_views', '0004_remove_commentbaseclass_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='دسته بندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='course.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان دوره')),
                ('description', models.TextField(verbose_name='توضیحات دوره')),
                ('image', models.ImageField(upload_to='course', verbose_name='تصویر دوره')),
                ('level', models.CharField(max_length=255, verbose_name='سطح دوره')),
                ('price', models.CharField(max_length=255, verbose_name='قیمت دوره')),
                ('course_status', models.CharField(max_length=255, verbose_name='وضعیت دوره')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(null=True, related_name='course_category', to='course.category')),
                ('student', models.ManyToManyField(blank=True, related_name='student_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان قسمت')),
                ('description', models.TextField(verbose_name='توضیحات قسمت')),
                ('video', models.FileField(null=True, upload_to='episodes/courses', verbose_name='ویدئو')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_episodes', to='course.course', verbose_name='قسمت های دوره')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت ها',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('commentbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common_views.commentbaseclass')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_of_courses', to='course.course', verbose_name='دوره')),
            ],
            bases=('common_views.commentbaseclass',),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(related_name='tags_of_course', to='course.tag', verbose_name='برچسب ها'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
