# Generated by Django 4.2.1 on 2023-08-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
