# Generated by Django 4.2.1 on 2023-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_discount_percentage_course_is_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(verbose_name='قیمت دوره'),
        ),
    ]
