# Generated by Django 4.2.1 on 2023-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت دوره'),
        ),
    ]
