# Generated by Django 4.2.1 on 2023-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
