# Generated by Django 4.2.1 on 2023-08-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
