# Generated by Django 4.2 on 2023-05-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_alter_episode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
