# Generated by Django 4.2 on 2023-05-23 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0015_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(editable=False, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='تعداد دیس لایک'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(editable=False, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='تعداد لایک'),
        ),
    ]
