# Generated by Django 4.2 on 2023-05-23 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0016_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='heart',
            field=models.ManyToManyField(editable=False, related_name='comment_hearts', to=settings.AUTH_USER_MODEL, verbose_name='تعداد قلب ها'),
        ),
    ]
