# Generated by Django 4.2.1 on 2023-08-28 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_discountnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountNotification',
        ),
    ]
