# Generated by Django 4.2 on 2023-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
