# Generated by Django 4.2.1 on 2023-08-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_counsel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('map-marker-alt', 'آدرس'), ('envelope', 'ایمیل'), ('phone', 'تلفن')], max_length=100)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField()),
                ('ways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_ways', to='contactus.way')),
            ],
        ),
    ]
