# Generated by Django 4.2.1 on 2023-08-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_remove_contactway_ways_contactway_ways'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'تلگرام'), ('youtube', 'یوتیوب'), ('instagram', 'اینستاگرام'), ('whatsapp', 'واتس اپ'), ('github', 'گیت هاب')], max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
